### ISSUE TITLE
Release 4.51?

### ISSUE THREAD

**Issue by eserte** [MartinMcGrath/CGI--Application#4]
Maybe https://metacpan.org/release/MARTO/CGI-Application-4.50_50 should be turned into a stable release?

**Comment by MaxPerl** [comment]
+1

**Comment by MartinMcGrath** [comment]
Hi guys,

Agreed, I'll do this in the next day or so, there are some other small POD
changes to reflect the new mailing list URL

**Comment by MartinMcGrath** [comment]
closing as 4.61 released.
